#import "../../utils.typ": *
== Ideals and Quotient Rings

=== Theory
#definition("Ideal")[
  An *ideal* $I$ of a ring $R$ is a subring such that for all $r in R$ and $x in I$, both $r dot x$ and $x dot r$ are in $I$. Ideals "absorb" multiplication by ring elements.
]

#definition("Principal Ideal")[
  If $R$ is a commutative ring with unity, the ideal generated by a single element $a in R$ is called a *principal ideal*. It is denoted by $chevron.l a chevron.r$ and consists of all multiples of $a$:
  $ chevron.l a chevron.r = \{r a : r in R\} $
]

#definition("Principal Ideal Domain (PID)")[
  A *Principal Ideal Domain* (or PID) is an integral domain in which every ideal is a principal ideal.
]

#example[
  The ring of integers $ZZ$ is a Principal Ideal Domain. Every ideal in $ZZ$ is of the form $n ZZ = chevron.l n chevron.r$ for some integer $n$.
]
#definition("Quotient Ring")[
  Given an ideal $I$, we can form the *quotient ring* $R slash I$. The elements of $R slash I$ are cosets $a + I$, and operations are defined naturally:
  - $(a + I) + (b + I) = (a + b) + I$
  - $(a + I) dot (b + I) = (a dot b) + I$
]



#proposition("Kernel is an Ideal")[
  The kernel of any ring homomorphism $phi: R arrow S$ is an ideal of $R$.
]

#proof[
  Let $K = ker(phi)$.
  1. *Subgroup*: $K$ is an additive subgroup (standard group theory result).
  2. *Absorption*: Let $r in R, k in K$.
    $phi(r dot k) = phi(r) dot phi(k) = phi(r) dot 0 = 0$.
    $phi(k dot r) = phi(k) dot phi(r) = 0 dot phi(r) = 0$.
    Thus $r dot k in K$ and $k dot r in K$, so $K$ is an ideal.
]



#definition("Prime Ideal")[
  An ideal $P$ of a commutative ring $R$ is called *prime* if $P eq.not R$ and, for all $a, b in R$,
  $ a b in P quad arrow.r.double quad a in P quad "or" quad b in P. $
]



#definition("Maximal Ideal")[
  An ideal $M$ of a ring $R$ is called *maximal* if $M eq.not R$ and there is no ideal $I$ of $R$ such that $M subset.neq I subset.neq R$. Equivalently, $M$ is maximal if the only ideals containing $M$ are $M$ itself and $R$.
]

#proposition("Characterizations of Prime and Maximal Ideals")[
  Let $R$ be a commutative ring with unity and $I$ a proper ideal of $R$. Then:
  + $I$ is prime if and only if $R slash I$ is an integral domain.
  + $I$ is maximal if and only if $R slash I$ is a field.
  + Every maximal ideal is prime.
]

#proof[
  *Part (1): $I$ prime $arrow.l.r.double$ $R slash I$ integral domain.*

  Recall that $R slash I$ is a commutative ring with unity $1 + I$ (inherited from $R$). We show the equivalence of the zero-divisor condition.

  Suppose $I$ is prime and $(a + I)(b + I) = 0 + I$ in $R slash I$. Then $a b in I$. Since $I$ is prime, $a in I$ or $b in I$, i.e., $a + I = 0$ or $b + I = 0$. Hence $R slash I$ has no zero divisors and is an integral domain.

  Conversely, suppose $R slash I$ is an integral domain and $a b in I$. Then $(a + I)(b + I) = a b + I = 0 + I$. Since $R slash I$ is an integral domain, $a + I = 0$ or $b + I = 0$, i.e., $a in I$ or $b in I$. Hence $I$ is prime.

  *Part (2): $I$ maximal $arrow.l.r.double$ $R slash I$ is a field.*

  Suppose $I$ is maximal. Since $R slash I$ is a commutative ring with unity, we need only show every non-zero element is invertible. Let $a + I eq.not 0 + I$, i.e., $a in.not I$. Consider the ideal $I + chevron.l a chevron.r = \{i + r a : i in I, r in R\}$. This strictly contains $I$ (since $a in.not I$), so by maximality $I + chevron.l a chevron.r = R$. Then $1 in R = I + chevron.l a chevron.r$, so $1 = i + r a$ for some $i in I, r in R$. In $R slash I$: $(r + I)(a + I) = r a + I = (1 - i) + I = 1 + I$. Thus $a + I$ has inverse $r + I$, and $R slash I$ is a field.

  Conversely, suppose $R slash I$ is a field. Let $J$ be an ideal with $I subset.neq J subset.eq R$ and pick $a in J without I$. Then $a + I eq.not 0$, so it has an inverse $b + I$ in $R slash I$: $a b + I = 1 + I$, giving $1 - a b in I subset.eq J$. Since $a in J$ we get $a b in J$, and thus $1 = (1 - a b) + a b in J$. Then $J = R$, so no proper ideal strictly contains $I$, making $I$ maximal.

  *Part (3): Every maximal ideal is prime.*

  If $I$ is maximal, then by Part (2) $R slash I$ is a field. Every field is an integral domain (a non-zero element has a multiplicative inverse, so it cannot be a zero divisor). By Part (1), $I$ is prime. $square$
]



=== Solved Problems

#solved_problem[
  Let $n in ZZ$. Prove formally that $n ZZ = \{n k : k in ZZ\}$ is an ideal of $ZZ$.
]
#proof[
  We verify the two conditions required by the definition of an ideal.

  *1. $n ZZ$ is an additive subgroup of $ZZ$.*

  - *Non-empty.* Since $n dot 0 = 0$, we have $0 in n ZZ$.

  - *Closed under subtraction.* Let $a, b in n ZZ$. Then $a = n j$ and $b = n k$ for some $j, k in ZZ$. Hence
    $ a - b = n j - n k = n(j - k). $
    Since $j - k in ZZ$, it follows that $a - b in n ZZ$.

  By the subgroup criterion, $n ZZ$ is an additive subgroup of $(ZZ, +)$.

  *2. $n ZZ$ absorbs multiplication by elements of $ZZ$.*

  Let $x in n ZZ$ and $r in ZZ$. Then $x = n k$ for some $k in ZZ$. We compute
  $ r x = r(n k) = n(r k) quad "and" quad x r = (n k) r = n(k r). $
  Since $ZZ$ is closed under multiplication, $r k in ZZ$ and $k r in ZZ$, so both $r x$ and $x r$ belong to $n ZZ$. (Note: because $ZZ$ is commutative, $r x = x r$, so the left and right absorption conditions coincide.)

  *Conclusion.* Since $n ZZ$ is a non-empty additive subgroup of $ZZ$ that is closed under left and right multiplication by any element of $ZZ$, it satisfies the definition of an ideal. Therefore $n ZZ$ is an ideal of $ZZ$. $square$
]

#solved_problem[
  Describe the elements of the quotient ring $ZZ slash 3ZZ$ and identify what it is isomorphic to.
]
#solution[
  Let $R = ZZ$ and $I = 3ZZ$. The elements of the quotient ring $ZZ slash 3ZZ$ are the cosets of $3ZZ$ in $ZZ$. By the Division Algorithm, every integer is congruent modulo 3 to exactly one of $0, 1, 2$, so there are exactly three distinct cosets:
  $ ZZ slash 3ZZ = \{0 + 3ZZ,quad 1 + 3ZZ,quad 2 + 3ZZ\}. $
  Addition and multiplication of cosets are defined by
  $ (a + 3ZZ) + (b + 3ZZ) = (a + b) + 3ZZ, quad (a + 3ZZ)(b + 3ZZ) = a b + 3ZZ. $
  The map $phi: ZZ slash 3ZZ -> ZZ_3$ defined by $phi(a + 3ZZ) = overline(a)$ is a well-defined ring isomorphism, so $ZZ slash 3ZZ tilde.eq ZZ_3$.
]

#solved_problem[
  Let $R$ be a ring and let $I, J$ be ideals of $R$. Show that the intersection $I inter J$ is also an ideal of $R$.
]
#proof[
  We verify the two ideal conditions for $I inter J$.

  *1. $I inter J$ is an additive subgroup of $R$.*

  - *Non-empty.* Since $I$ and $J$ are ideals they both contain $0$, so $0 in I inter J$.

  - *Closed under subtraction.* Let $a, b in I inter J$. Then $a, b in I$ and $a, b in J$. Since $I$ is an additive subgroup, $a - b in I$; since $J$ is an additive subgroup, $a - b in J$. Therefore $a - b in I inter J$.

  By the subgroup criterion, $I inter J$ is an additive subgroup of $(R, +)$.

  *2. $I inter J$ absorbs multiplication by elements of $R$.*

  Let $x in I inter J$ and $r in R$. Then $x in I$, and since $I$ is an ideal, $r x in I$ and $x r in I$. Likewise $x in J$, so $r x in J$ and $x r in J$. Therefore $r x in I inter J$ and $x r in I inter J$.

  *Conclusion.* $I inter J$ is a non-empty additive subgroup of $R$ that absorbs multiplication on both sides, so it is an ideal of $R$. $square$
]

#solved_problem[
  Let $phi: ZZ[x] -> ZZ$ be the evaluation homomorphism defined by $phi(f) = f(2)$. Show that $phi$ is a ring homomorphism and identify its kernel as a principal ideal.
]
#proof[
  *Step 1: $phi$ is a ring homomorphism.*

  For any $f, g in ZZ[x]$ and using standard polynomial arithmetic:
  $ phi(f + g) = (f + g)(2) = f(2) + g(2) = phi(f) + phi(g), $
  $ phi(f dot g) = (f dot g)(2) = f(2) dot g(2) = phi(f) dot phi(g), $
  $ phi(1) = 1. $
  Hence $phi$ is a ring homomorphism.

  *Step 2: $ker(phi)$ is an ideal.*

  By the Kernel-is-an-Ideal Proposition, $ker(phi) = \{f in ZZ[x] : f(2) = 0\}$ is an ideal of $ZZ[x]$.

  *Step 3: Identifying the kernel.*

  A polynomial $f in ZZ[x]$ satisfies $f(2) = 0$ if and only if $(x - 2) divides f(x)$ in $ZZ[x]$ (Factor Theorem). Therefore
  $ ker(phi) = chevron.l x - 2 chevron.r = \{(x-2) g(x) : g in ZZ[x]\}, $
  which is the principal ideal generated by $x - 2$. $square$
]

#solved_problem[
  Let $p$ be a prime integer. Show that $p ZZ$ is a maximal ideal of $ZZ$, and conclude that the quotient ring $ZZ slash p ZZ$ is a field.
]
#proof[
  *Step 1: $p ZZ$ is an ideal of $ZZ$.*

  By the first solved problem (applied with $n = p$), $p ZZ$ is an ideal of $ZZ$.

  *Step 2: $p ZZ$ is maximal.*

  Suppose $I$ is an ideal of $ZZ$ with $p ZZ subset.neq I subset.eq ZZ$. Since every ideal of $ZZ$ is principal, $I = d ZZ$ for some $d in ZZ$. The inclusion $p ZZ subset.eq d ZZ$ means $d divides p$. Since $p$ is prime, its only divisors are $plus.minus 1$ and $plus.minus p$, giving either $d ZZ = ZZ$ or $d ZZ = p ZZ$. The strict inclusion forces $I = d ZZ = ZZ$. Hence no ideal lies strictly between $p ZZ$ and $ZZ$, so $p ZZ$ is maximal.

  *Step 3: $ZZ slash p ZZ$ is a field.*

  A standard theorem states that an ideal $M$ of a commutative ring $R$ is maximal if and only if $R slash M$ is a field. Since $p ZZ$ is maximal in $ZZ$, we conclude
  $ ZZ slash p ZZ tilde.eq ZZ_p $
  is a field. $square$
]

#solved_problem[
  In $ZZ[x]$, let $I = chevron.l x^2 + 1 chevron.r$. Describe the elements of $ZZ[x] slash I$.
]
#solution[
  Elements of the quotient are polynomials modulo $x^2 + 1$.
  By the Division Algorithm for polynomials, any $f(x) in ZZ[x]$ can be written as:
  $f(x) = q(x)(x^2 + 1) + r(x)$, where $deg(r) < 2$.

  Thus, every coset has a unique representative of the form $a x + b$ where $a, b in ZZ$.
  Multiplication satisfies $x^2 equiv -1$.
  This ring is isomorphic to the Gaussian integers $ZZ[i]$ via the map $a x+b mapsto b i + a$.
]

=== Self-Evaluation Quiz

#quiz[
  #question(
    [An ideal $I$ of a ring $R$ is a subring that absorbs:],
    ("Multiplication", "Addition", "Division", "Inverses"),
    0,
  )

  #question(
    [If $R$ is a commutative ring with unity, the ideal generated by a single element $a$, denoted $chevron.l a chevron.r$, is called:],
    ("Principal Ideal", "Prime Ideal", "Maximal Ideal", "Null Ideal"),
    0,
  )

  #question(
    [Properties of Ideal $I$: Which statement is true?],
    ([$0 in I$], [$1 in I$ is required], [$I$ must be finite], [$I = R$ always]),
    0,
  )

  #question(
    [In the quotient ring $R/I$, the zero element is:],
    ([The ideal $I$ itself], [The element 0], [The element 1], [Undefined]),
    0,
  )

  #question(
    [A generic element of the quotient ring $R/I$ is a:],
    ("Coset", "Vector", "Scalar", "Matrix"),
    0,
  )

  #question(
    [An ideal $M$ is maximal if:],
    ([The only ideal properly containing $M$ is $R$], [It contains all divisors], [It is infinite], [It is principal]),
    0,
  )

  #question(
    [The quotient ring $R/M$ is a field if and only if $M$ is:],
    ("Maximal", "Prime", "Principal", "Zero"),
    0,
  )

  #question(
    [An ideal $P$ is prime if $a b in P$ implies:],
    ([$a in P$ or $b in P$], [$a in P$ and $b in P$], [$a = 0$], [$b = 0$]),
    0,
  )

  #question(
    [The kernel of a ring homomorphism $phi: R arrow S$ is always:],
    ("An ideal of R", "A subring of S", "Isomorphic to S", "Empty"),
    0,
  )

  #question(
    [In $ZZ$, every ideal is:],
    ("Principal", "Maximal", "Prime", "Finite"),
    0,
  )
]

=== Supplementary Problems

#supplementary[
  Let $R$ be a commutative ring with unity. Show that $R$ is a field if and only if its only ideals are $\{0\}$ and $R$ itself.
]

#supplementary[
  Let $I$ be the set of matrices in $M_2(RR)$ with the first column equal to zero. Is $I$ a left ideal, right ideal, or two-sided ideal?
]

#supplementary[
  Find all ideals of the ring $ZZ_(12)$.
]

#supplementary[
  Determine if the ideal $I = chevron.l x^2 + 1 chevron.r$ is prime or maximal in $RR[x]$.
]

#supplementary[
  Let $phi: R arrow S$ be a ring homomorphism. Prove that the image $Im(phi)$ is a subring of $S$.
]

#supplementary[
  In the ring $ZZ$, describe the ideal $I = 4ZZ + 6ZZ$.
]

#supplementary[
  Consider the quotient ring $R = ZZ_(2)[x] slash chevron.l x^2 + x + 1 chevron.r$. List all its elements.
]

#supplementary[
  Show that the intersection of two ideals $I$ and $J$ is also an ideal.
]

#supplementary[
  Is the set of polynomials with constant term zero, $I = \{f(x) in ZZ[x] : f(0)=0\}$, an ideal of $ZZ[x]$?
]

#supplementary[
  Find a non-trivial ideal in the ring $ZZ_(10)$.
]


