#import "../../utils.typ": *
== Subgroups

=== Theory
#definition("Subgroup")[
  A subset $H$ of a group $G$ is called a *subgroup* if $H$ itself forms a group under the same operation defined on $G$. We denote this as $H lt.eq G$.
]

#proposition("Subgroup Test")[
  A non-empty subset $H subset.eq G$ is a subgroup if and only if for all $a, b in H$, $a dot b^(-1) in H$.
]

#theorem("Lagrange's Theorem")[
  If $G$ is a finite group and $H$ is a subgroup of $G$, then the order (number of elements) of $H$ divides the order of $G$. i.e., $|H|$ divides $|G|$.
  #proof[
    The left cosets of $H$ in $G$ form a partition of $G$. The map $h mapsto g h$ is a bijection between $H$ and $g H$, so every coset has the same size $|H|$. If there are $k$ distinct cosets, then $|G| = k |H|$. Thus $|H|$ divides $|G|$.
  ]
]

#example[
  *Small Subgroup Attacks*: Subgroups play a crucial role in preventing "small subgroup attacks" in cryptographic protocols. In Diffie-Hellman, if the group order has small factors, an attacker can confine the shared secret to a small subgroup and exhaustively search for it. We often choose groups of prime order or groups where the order has a large prime factor to avoid this.
]

=== Solved Problems

#solved_problem[
  *Finding Subgroups*
  Find all subgroups of $ZZ_6$ (under addition).
]
#solution[
  The order of $ZZ_6$ is 6. By Lagrange's Theorem, possible orders for subgroups are divisors of 6: 1, 2, 3, 6.
  - Order 1: ${0}$ (trivial subgroup).
  - Order 2: Elements of order 2 satisfy $x+x = 2x = 0$. In $ZZ_6$, $2(3) = 6 equiv 0$. Subgroup: ${0, 3}$.
  - Order 3: Elements of order 3 satisfy $3x = 0$. $2(3)=6equiv 0$ and $4(3)=12equiv 0$. Subgroup: ${0, 2, 4}$.
  - Order 6: $ZZ_6$ itself.
]

#solved_problem[
  Let $G = ZZ_7^*$ (under multiplication). Find the subgroup generated by the element $2$.
]
#solution[
  $ZZ_7^* = {1, 2, 3, 4, 5, 6}$.
  We calculate powers of 2 modulo 7:
  $2^1 = 2$
  $2^2 = 4$
  $2^3 = 8 equiv 1 (mod 7)$
  Since we reached the identity, the subgroup generated by 2 is $<2> = {1, 2, 4}$. Example order is 3.
]

#solved_problem[
  Propose a reason why we might want to use a subgroup of prime order for cryptography.
]
#solution[
  Prime order subgroups have no proper non-trivial subgroups (Lagrange's Theorem: divisors of prime $p$ are only 1 and $p$). This prevents small subgroup attacks where an attacker forces the computation into a smaller group to solve the discrete logarithm problem more easily. If the group has prime order, the attacker cannot force the key into a non-trivial subgroup.
]

=== Supplementary Problems

#supplementary[
  List all subgroups of $ZZ_(12)$.
]

#supplementary[
  Show that the intersection of two subgroups $H$ and $K$ of a group $G$ is also a subgroup of $G$.
]
