#import "../../utils.typ": *
== Subgroups

=== Theory
#definition("Subgroup")[
  A subset $H$ of a group $G$ is called a *subgroup* if $H$ itself forms a group under the same operation defined on $G$. We denote this as $H lt.eq G$.
]

#definition("Center of a Group")[
  The *center* of a group $G$, denoted $Z(G)$, is the subset of elements in $G$ that commute with every element of $G$:
  $ Z(G) = {z in G | z g = g z " for all " g in G} $
  The center is always a normal subgroup of $G$. If $G$ is abelian, then $Z(G) = G$.
]

#definition("Centralizer and Normalizer")[
  For a subset $S$ of a group $G$, the *centralizer* of $S$, denoted $C(S)$, is the set of elements in $G$ that commute with every element of $S$.
  The *normalizer* of $S$, denoted $N(S)$, is the set of elements $g in G$ such that $g S g^(-1) = S$.
  Both $C(S)$ and $N(S)$ are subgroups of $G$, and $C(S) subset.eq N(S)$.
]


#proposition("Subgroup Test")[
  A non-empty subset $H subset.eq G$ is a subgroup if and only if for all $a, b in H$, $a dot b^(-1) in H$.
]

#proof[
  $(=>)$ Suppose $H$ is a subgroup of $G$. Let $a, b in H$. Since $H$ is a group, $b^(-1) in H$. By closure, $a dot b^(-1) in H$.

  $(<=)$ Suppose $H != emptyset$ and for all $a, b in H$, $a dot b^(-1) in H$.
  1. *Identity*: Since $H != emptyset$, there exists $x in H$. Let $a = x, b = x$. Then $x dot x^(-1) = e in H$.
  2. *Inverses*: Let $x in H$. Set $a = e, b = x$. Then $e dot x^(-1) = x^(-1) in H$.
  3. *Closure*: Let $x, y in H$. Since $y in H$, we have $y^(-1) in H$ (from 2). Set $a = x, b = y^(-1)$. Then $x dot (y^(-1))^(-1) = x dot y in H$.
  4. *Associativity*: Inherited from $G$.
  Thus, $H$ is a subgroup.
]

#theorem("Lagrange's Theorem")[
  If $G$ is a finite group and $H$ is a subgroup of $G$, then the order (number of elements) of $H$ divides the order of $G$. i.e., $|H|$ divides $|G|$.
]

#proof[
  The left cosets of $H$ in $G$ form a partition of $G$. The map $h mapsto g h$ is a bijection between $H$ and $g H$, so every coset has the same size $|H|$. If there are $k$ distinct cosets, then $|G| = k |H|$. Thus $|H|$ divides $|G|$.
]


=== Solved Problems

#solved_problem[
  Prove that the set of even integers $2ZZ$ is a subgroup of the integers $ZZ$ under addition.
]
#solution[
  We verify the subgroup properties for $2ZZ = {..., -4, -2, 0, 2, 4, ...}$:
  - *Subset*: Clearly $2ZZ subset ZZ$.
  - *Identity*: $0 = 2(0) in 2ZZ$.
  - *Closure*: If $a = 2m$ and $b = 2n$, then $a + b = 2(m+n)$, which is even.
  - *Inverses*: If $a = 2m$, then $-a = 2(-m)$, which is even.
]

#solved_problem[
  Explain how subgroups can lead to "small subgroup attacks" in cryptographic protocols like Diffie-Hellman, and how to mitigate them.
]
#solution[
  In Diffie-Hellman, we work in a group $Z_p^*$. If order $p-1$ has a small factor $q$, there exists a subgroup of order $q$.
  An attacker can send a value $h$ of order $q$. Then the shared secret $s = h^a$ will also be in this small subgroup. The attacker can brute-force $s$ in $O(q)$ steps, revealing information about the private key $a$.
  *Mitigation*: Use groups of prime order, or verify that received elements are in the correct subgroup.
]

#solved_problem[
  *Finding Subgroups*
  Find all subgroups of $ZZ_6$ (under addition).
]
#solution[
  The order of $ZZ_6$ is 6. By *Lagrange's Theorem*, the order of any subgroup must divide 6. Divisors are 1, 2, 3, 6.
  We investigate cyclic subgroups generated by each element:
  - $<0> = {0}$. Order 1.
  - $<1> = {0, 1, 2, 3, 4, 5} = ZZ_6$. Order 6.
  - $<2> = {0, 2, 2+2, ...} = {0, 2, 4}$. Order 3 ($3 times 2 = 6 equiv 0$).
  - $<3> = {0, 3}$. Order 2 ($2 times 3 = 6 equiv 0$).
  - $<4> = {0, 4, 8 equiv 2, 2+4=6 equiv 0} = {0, 4, 2}$. Same as $<2>$.
  - $<5> = {0, 5, 10 equiv 4, 15 equiv 3, 20 equiv 2, 25 equiv 1} = ZZ_6$.

  Summary of distinct subgroups:
  1. ${0}$ (Order 1)
  2. ${0, 3}$ (Order 2)
  3. ${0, 2, 4}$ (Order 3)
  4. $ZZ_6$ (Order 6)
]

#solved_problem[
  Let $G = ZZ_7^*$ (under multiplication). Find the subgroup generated by the element $2$.
]
#solution[
  $ZZ_7^* = {1, 2, 3, 4, 5, 6}$. Operation is multiplication modulo 7.
  We compute the powers of 2 until we reach the identity (1):
  1. $2^1 = 2$
  2. $2^2 = 4$
  3. $2^3 = 8$. Dividing 8 by 7 gives remainder 1 ($8 equiv 1 mod 7$).

  Since we reached 1, the sequence repeats.
  The subgroup generated by 2 is $<2> = {1, 2, 4}$.
  The order of this subgroup is 3. Note that 3 divides $|ZZ_7^*| = 6$.
]

#solved_problem[
  Propose a reason why we might want to use a subgroup of prime order for cryptography.
]
#solution[
  Cryptography often relies on the *Discrete Logarithm Problem* in a group $G$. The hardness of this problem depends on the size of the prime factor of the group order.
  - If the group order $n$ is composite (e.g., $n = a dot b$), there exist subgroups of order $a$ and $b$.
  - An attacker can use the *Pohlig-Hellman algorithm* to solve the problem in the smaller subgroups and combine the results (using CRT), which is much faster than solving it in $G$.
  - By choosing a group of *prime order* $p$, the only subgroups are the trivial one $\{e\}$ and $G$ itself. This forces the attacker to solve the problem in the full group $G$, maximizing security.
]


=== Self-Evaluation Quiz

#quiz[
  #question(
    [Which result states that the order of a subgroup divides the order of the group?],
    ("Cayley's Theorem", "Lagrange's Theorem", "Euler's Theorem", "Fermat's Little Theorem"),
    1,
  )

  #question(
    [The intersection of two subgroups $H$ and $K$ is:],
    ("Always a subgroup", "Never a subgroup", [A subgroup only if $G$ is abelian], "Empty"),
    0,
  )

  #question(
    [The center of a group $Z(G)$ acts as the:],
    ("Set of generators", "Identity subgroup", [Set of elements that commute with all of $G$], "Set of inverses"),
    2,
  )

  #question(
    [Which of the following are always subgroups of any group $G$?],
    ([Only ${e}$], [Only $G$], [${e}$ and $G$], [None]),
    2,
  )

  #question(
    [The One-Step Subgroup Test states that a non-empty subset $H$ is a subgroup if for all $a, b in H$:],
    ([$a b in H$], [$a^(-1) in H$], [$a b^(-1) in H$], [$a + b in H$]),
    2,
  )

  #question(
    [The intersection of any collection of subgroups of $G$ is:],
    ([Always a subgroup], [Never a subgroup], [A subgroup only if finite], [Empty]),
    0,
  )

  #question(
    [The cyclic subgroup generated by $g$, denoted $<g>$, consists of:],
    ([$\{g, g^(-1)\}$], [$\{g^n : n in ZZ\}$], [$\{g^n : n in NN\}$], [$\{e, g\}$]),
    1,
  )

  #question(
    [A left coset of a subgroup $H$ containing $g$ is defined as $g H =$:],
    ([$\{g h : h in H\}$], [$\{h g : h in H\}$], [$\{h : h in H\}$], [$\{g\}$]),
    0,
  )

  #question(
    [The index of a subgroup $H$ in $G$, denoted $[G:H]$, represents:],
    (
      [The order of $H$],
      [The number of elements in $G$],
      [The number of distinct left cosets of $H$],
      [The order of $G$ minus order of $H$],
    ),
    2,
  )

  #question(
    [True or False: If the order of a subset $H$ divides the order of $G$, then $H$ must be a subgroup (Converse of Lagrange).],
    ("True", "False", "Only for abelian groups", "Only for finite groups"),
    1,
  )
]

=== Supplementary Problems

#supplementary[
  List all subgroups of $ZZ_(12)$.
]

#supplementary[
  Show that the intersection of two subgroups $H$ and $K$ of a group $G$ is also a subgroup of $G$.
]

#supplementary[
  Find the center of the group $S_3$. The center $Z(G)$ is the set of elements that commute with all elements of $G$.
]

#supplementary[
  Let $H$ and $K$ be subgroups of $G$. Prove that their union $H union K$ is a subgroup if and only if $H subset.eq K$ or $K subset.eq H$.
]

#supplementary[
  Find all subgroups of $Z_8$.
]

#supplementary[
  State the One-Step Subgroup Test: A non-empty subset $H$ of a group $G$ is a subgroup if and only if for all $a, b in H$, $a b^(-1) in H$. Use it to prove that $5ZZ$ is a subgroup of $ZZ$.
]

#supplementary[
  Define the *normalizer* of a set $S$ in $G$ as $N(S) = {g in G | g S g^(-1) = S}$. Show that $N(S)$ is a subgroup of $G$.
]

#supplementary[
  Let $g$ be an element of a group $G$ with order $n$. Show that the cyclic subgroup generated by $g$, $<g>$, also has order $n$.
]

#supplementary[
  List all generators of the cyclic group $ZZ_(18)$. How many are there?
]

#supplementary[
  If $H$ is a subgroup of $G$, the *index* of $H$ in $G$, denoted $[G : H]$, is the number of distinct left cosets of $H$. Calculate $[S_3 : <(1 space 2)>]$.
]
