#import "../../utils.typ": *

== Sylow Theorems

=== Theory

#definition("$p$-group and Sylow $p$-subgroup")[
  Let $G$ be a finite group and $p$ a prime number.
  - A *$p$-group* is a group where the order of every element is a power of $p$. For finite groups, this is equivalent to the order of the group being $p^k$ for some integer $k >= 1$.
  - Let $|G| = p^n m$ where $n >= 1$ and $p$ does not divide $m$. A subgroup of $G$ of order $p^n$ is called a *Sylow $p$-subgroup* of $G$.
]

#theorem("First Sylow Theorem (Existence)")[
  Let $G$ be a finite group of order $p^n m$, where $p$ is prime and $p$ does not divide $m$. Then $G$ contains at least one Sylow $p$-subgroup of order $p^n$.
  (More generally, if $p^k$ divides $|G|$, then $G$ has a subgroup of order $p^k$).
]

#theorem("Second Sylow Theorem (Conjugacy)")[
  Any two Sylow $p$-subgroups of a finite group $G$ are conjugate. That is, if $P_1$ and $P_2$ are Sylow $p$-subgroups of $G$, then there exists an element $g in G$ such that $P_2 = g P_1 g^(-1)$.
  Furthermore, any $p$-subgroup of $G$ is contained in some Sylow $p$-subgroup.
]

#theorem("Third Sylow Theorem (Quantity)")[
  Let $n_p$ be the number of Sylow $p$-subgroups of $G$. Then:
  1. $n_p equiv 1 (mod p)$
  2. $n_p$ divides $m$ (where $|G| = p^n m$)
  3. $n_p = |G : N(P)|$, where $N(P)$ is the normalizer of any Sylow $p$-subgroup $P$.
]

#proposition("Normal Sylow p-subgroups")[
  A Sylow $p$-subgroup $P$ of $G$ is a normal subgroup of $G$ ($P triangle.l G$) if and only if it is the *unique* Sylow $p$-subgroup of $G$ (i.e., $n_p = 1$).
]


=== Solved Problems

#solved_problem[
  Prove that any group $G$ of order 15 is cyclic.
]
#solution[
  Let $|G| = 15 = 3 times 5$.
  By the Third Sylow Theorem, the number of Sylow 3-subgroups $n_3$ must divide 5 and satisfy $n_3 equiv 1 (mod 3)$. The only divisor of 5 that is $1 mod 3$ is $1$. Thus, $n_3 = 1$, making the unique Sylow 3-subgroup (let's call it $P_3$) normal in $G$.

  Similarly, the number of Sylow 5-subgroups $n_5$ must divide 3 and satisfy $n_5 equiv 1 (mod 5)$. The only such divisor is $1$. Thus, $n_5 = 1$, making the unique Sylow 5-subgroup $P_5$ normal in $G$.

  Since $P_3$ and $P_5$ are normal, their intersection is just the identity $\{e\}$ (their orders are coprime). They generate the whole group $G$ because $|P_3| times |P_5| = 15$.
  Therefore, $G tilde.eq P_3 times P_5$.
  Since $P_3 tilde.eq ZZ_3$ and $P_5 tilde.eq ZZ_5$, we have $G tilde.eq ZZ_3 times ZZ_5 tilde.eq ZZ_(15)$, which is cyclic.
]

#solved_problem[
  Show that no group of order 30 is simple.
]
#solution[
  Recall that a group is simple if its only normal subgroups are the trivial group and itself. Let $|G| = 30 = 2 times 3 times 5$.
  Assume for contradiction that $G$ is simple. Then no Sylow subgroup can be unique (otherwise it would be normal).
  - The number $n_5$ of Sylow 5-subgroups divides $6$ and is $1 mod 5$. So $n_5 = 6$.
    Since they have prime order 5, they intersect trivially. Thus, there are $6 times (5-1) = 24$ elements of order 5.
  - The number $n_3$ of Sylow 3-subgroups divides $10$ and is $1 mod 3$. So $n_3 = 10$.
    Since they have prime order 3, they intersect trivially. Thus, there are $10 times (3-1) = 20$ elements of order 3.

  Adding just the elements of order 5 and order 3 gives $24 + 20 = 44$ elements. But the group only has 30 elements in total!
  This is a contradiction. Therefore, at least one of the Sylow subgroups must be unique, meaning it is normal. Thus $G$ cannot be simple.
]

#solved_problem[
  Find all the Sylow 2-subgroups and Sylow 3-subgroups of the symmetric group $S_3$.
]
#solution[
  The order of $S_3$ is $6 = 2^1 times 3^1$.
  - *Sylow 3-subgroups*: Order is 3. The 3-cycles generate these. There is only one subgroup of order 3: $A_3 = {id, (1 space 2 space 3), (1 space 3 space 2)}$. Since $n_3 = 1$, it is normal.
  - *Sylow 2-subgroups*: Order is 2. These are generated by the transpositions. There are three such subgroups:
    $P_1 = {id, (1 space 2)}$, $P_2 = {id, (1 space 3)}$, $P_3 = {id, (2 space 3)}$.
    So $n_2 = 3$ (which divides 3 and is $1 mod 2$). Since $n_2 > 1$, they are not normal.
]


=== Self-Evaluation Quiz

#quiz[
  #question(
    [A $p$-group is a group where the order of every element is:],
    (
      "A prime $p$",
      "A power of $p$",
      "A multiple of $p$",
      "Coprime to $p$",
    ),
    1,
  )

  #question(
    [If $|G| = p^n m$ where $p$ is prime and $p$ does not divide $m$, a Sylow $p$-subgroup has order:],
    (
      "$m$",
      "$p$",
      "$p^n$",
      "$n$",
    ),
    2,
  )

  #question(
    [The First Sylow Theorem guarantees the existence of subgroups of what order?],
    (
      [Any order dividing $|G|$],
      [Order $p^k$ where $p^k$ divides $|G|$],
      [Only order $p$],
      [Order $m$],
    ),
    1,
  )

  #question(
    [According to the Second Sylow Theorem, any two Sylow $p$-subgroups of $G$ are:],
    (
      "Isomorphic but not conjugate",
      "Conjugate (and thus isomorphic)",
      "Disjoint",
      "Normal",
    ),
    1,
  )

  #question(
    [The Third Sylow Theorem states that the number of Sylow $p$-subgroups $n_p$ must be congruent to:],
    (
      [$0 mod p$],
      [$1 mod p$],
      [$p mod 1$],
      [$-1 mod p$],
    ),
    1,
  )

  #question(
    [The number of Sylow $p$-subgroups $n_p$ must also divide:],
    (
      [$p$],
      [$n$],
      [$m$, where $|G| = p^n m$],
      [$p^n$],
    ),
    2,
  )

  #question(
    [A Sylow $p$-subgroup $P$ is normal in $G$ if and only if $n_p =$ ?],
    (
      [$0$],
      [$1$],
      [$p$],
      [$m$],
    ),
    1,
  )

  #question(
    [If a group $G$ has order 45 ($3^2 times 5$), what are the possible values for $n_5$?],
    (
      [1],
      [1 or 5],
      [1 or 3],
      [1 or 9],
    ),
    0,
  )

  #question(
    [In a group of order 15, the unique Sylow 3-subgroup and Sylow 5-subgroup implies the group is:],
    (
      "Non-abelian",
      "Simple",
      "Cyclic",
      "Symmetric",
    ),
    2,
  )

  #question(
    [Which of the following orders of a group makes it impossible to be a simple group?],
    (
      [2],
      [3],
      [5],
      [30],
    ),
    3,
  )
]


=== Supplementary Problems

#supplementary[
  Determine all possible numbers of Sylow 2-subgroups and Sylow 3-subgroups in a group of order 12.
]

#supplementary[
  Prove that no group of order $p q$, where $p$ and $q$ are distinct primes with $p < q$ and $p$ does not divide $q-1$, can be simple.
]

#supplementary[
  Let $G$ be a group of order 45. Prove that the Sylow 3-subgroup of $G$ is normal.
]

#supplementary[
  Show that a group of order 200 has a normal Sylow 5-subgroup.
]

#supplementary[
  Is the reverse of the Second Sylow theorem true? That is, if two subgroups of a finite group are conjugate, do they have to be Sylow $p$-subgroups?
]

#supplementary[
  Find the order of the normalizer of a Sylow 2-subgroup in $S_3$.
]

#supplementary[
  Explain why the intersection of two distinct Sylow $p$-subgroups forming a subgroup of maximum possible order is a powerful step in verifying non-simplicity of large groups.
]

#supplementary[
  Let $G$ be a group of order $p^n$ where $p$ is a prime. Prove that the center $Z(G)$ is non-trivial (has order $> 1$). (Hint: Use the class equation).
]
