#import "../../utils.typ": *

== Normal Basis Arithmetic

=== Theory

#definition("Normal Basis")[
  A *normal basis* of $"GF"(p^n)$ over $"GF"(p)$ is a basis of the form:
  $ N = {beta, beta^p, beta^(p^2), ..., beta^(p^(n-1))} $
  where $beta in "GF"(p^n)$.
]

#theorem("Squaring in Normal Basis")[
  In a normal basis representation over $"GF"(2^n)$, squaring an element is a simple *cyclic shift* of its coordinates.
  If $A = (a_0, a_1, ..., a_(n-1))$ represents $a_0 beta + a_1 beta^2 + ...$, then
  $ A^2 = (a_(n-1), a_0, a_1, ..., a_(n-2)) $

  #align(center)[
    #box(stroke: 1pt + gray, inset: 10pt, radius: 5pt)[
      *Cyclic Shift Operation:* \
      $(a_0, a_1, a_2) arrow.r^"Square" (a_2, a_0, a_1) arrow.r^"Square" (a_1, a_2, a_0)$
    ]
  ]
  This makes squaring extremely efficient in hardware.
]

=== Solved Problems

#solved_problem[
  Given a normal basis element $A = (1, 0, 1)$ in $"GF"(2^3)$, compute $A^2$ and $A^4$.
]
#solution[
  $A = (1, 0, 1)$ corresponds to coefficients for $beta, beta^2, beta^4$.
  Squaring is a right cyclic shift (or left depending on indexing convention, here assuming $A^2$ shifts right):
  $ A^2 = (1, 1, 0) $
  Squaring again:
  $ A^4 = (0, 1, 1) $
  Squaring again gives $A^8 = (1, 0, 1) = A$ (since $2^3 = 8$, $x^8 = x$ in the field).
]

#solved_problem[
  Convert the polynomial $x^2 + 1$ in $"GF"(2^3)$ to its Normal Basis representation, given the normal basis $N = {x^3, x^6, x^12 mod P(x)}$ where $P(x) = x^3 + x^2 + 1$.
  (Note: $x^3 = x^2 + 1$ in this field).
]
#solution[
  Let the basis elements be $beta_1 = x^3$, $beta_2 = x^6$, $beta_4 = x^12$.
  First, express the target polynomial $T = x^2 + 1 = x^3$ (using relation $x^3 + x^2 + 1 = 0$).
  So $T = beta_1$.
  The coordinate vector is $(1, 0, 0)$.
  Let's verify: $1 dot beta_1 + 0 dot beta_2 + 0 dot beta_4 = x^3 = x^2 + 1$. Correct.
]

=== Self-Evaluation Quiz

#quiz[
  #question(
    [A Normal Basis for $"GF"(p^n)$ is generated by repeated application of which map?],
    (
      [Frobenius Map ($x arrow x^p$)],
      [Inversion Map ($x arrow x^(-1$))],
      [Shift Map ($x arrow x+1$)],
      [Identity Map ($x arrow x$)],
    ),
    0,
  )

  #question(
    [In a Normal Basis over $"GF"(2^n)$, squaring an element corresponds to:],
    (
      "A complex multiplication",
      "A cyclic shift of coordinates",
      "Inverting the bits",
      "Adding 1 to the first coordinate",
    ),
    1,
  )

  #question(
    [The squaring operation in Normal Basis is often described as being:],
    (
      "Free (cost-wise) in hardware",
      "Extremely expensive",
      "Impossible to implement",
      "Slower than multiplication",
    ),
    0,
  )

  #question(
    [If $beta$ generates a normal basis ${beta, beta^p, ..., beta^(p^(n-1))}$, then all elements in the basis are:],
    (
      "Conjugates of each other",
      "Inverses of each other",
      "Primitive roots",
      "Linearly dependent",
    ),
    0,
  )

  #question(
    [Multiplication of two elements in Normal Basis is generally:],
    (
      "Simpler than in Polynomial Basis",
      "More complex and requires a multiplication matrix ($lambda$-matrix)",
      "Identical to integer multiplication",
      "Not defined",
    ),
    1,
  )

  #question(
    [To compute the square root of an element in Normal Basis over $"GF"(2^n)$, one performs:],
    (
      "A left cyclic shift (inverse of squaring)",
      "Standard square root algorithm",
      "Exhaustive search",
      "It cannot be done",
    ),
    0,
  )

  #question(
    [Converting between Polynomial Basis and Normal Basis:],
    (
      "Is impossible",
      "Requires a linear transformation (matrix multiplication)",
      "Is always the identity mapping",
      "Requires solving ECDLP",
    ),
    1,
  )

  #question(
    [The trace of an element $"Tr"(alpha) = sum alpha^(p^i)$ maps an element from $"GF"(p^n)$ to:],
    (
      [The base field $"GF"(p)$],
      [The extension field $"GF"(p^n)$],
      [The integers $ZZ$],
      [The complex numbers $CC$],
    ),
    0,
  )

  #question(
    [In Normal Basis, raising an element to the power $2^k$ (in characteristic 2) corresponds to:],
    (
      [$k$ cyclic shifts],
      [$k$ multiplications],
      [$2^k$ additions],
      [No operation],
    ),
    0,
  )

  #question(
    [Which standard mandates the use of either Polynomial Basis or Optimal Normal Basis for binary curves?],
    (
      "NIST FIPS 186-4 (and others)",
      "HTML5",
      "TCP/IP",
      "JSON",
    ),
    0,
  )
]

=== Supplementary Problems

#supplementary[
  Explain why the multiplication operation is generally more complex in normal basis representation compared to polynomial basis representation.
]

#supplementary[
  Verify that for any element $alpha in "GF"(2^n)$, $"Tr"(alpha) = 1$ if and only if $alpha$ has an odd number of 1s in its normal basis representation (assuming Trace definition involving sum of conjugates).
]

#supplementary[
  Given the normal basis $N = {beta, beta^2, beta^4}$ for $"GF"(2^3)$, express the element $beta + beta^2$ as a vector.
]

#supplementary[
  Compute the square of $A = (0, 1, 1)$ in a normal basis for $"GF"(2^3)$.
]

#supplementary[
  Compute the square root of $A = (1, 0, 1)$ in a normal basis for $"GF"(2^3)$. (Hint: Inverse of cyclic shift).
]

#supplementary[
  If $A = (a_0, a_1, ..., a_(n-1))$ in Normal Basis, what is the representation of $A^(2^k)$?
]

#supplementary[
  Convert the vector $(1, 1, 0)$ from Normal Basis $N={x^3, x^6, x^12}$ to Polynomial Basis ${1, x, x^2}$ in $"GF"(2^3)$ modulo $x^3+x^2+1$.
]

#supplementary[
  Why is Normal Basis preferred for hardware implementations where frequent squaring is required (e.g., inversion using Fermat's Little Theorem)?
]

#supplementary[
  Show that the sum of all elements in a normal basis is equal to the trace of the generator $beta$.
]

#supplementary[
  Construct a normal basis for $"GF"(2^2)$ over $"GF"(2)$. (Find $\beta$ such that ${\beta, \beta^2}$ is linearly independent).
]
