#import "../../utils.typ": *
== Diffie-Hellman over Elliptic Curves over $FF_p$

=== Theory

Section 3.3 built a finite abelian group from the points of an elliptic curve over $FF_p$. This section uses that group to describe elliptic-curve Diffie-Hellman. The protocol is not based on multiplying field elements; it is based on scalar multiplication of points.

#definition("Scalar Multiplication")[
  *Scalar multiplication* is repeated use of the elliptic-curve operation $⊕$:
  $ k P = underbrace(P ⊕ P ⊕ ... ⊕ P)_(k " times"). $
  It is computed efficiently by the *double-and-add algorithm*, which uses the binary expansion of $k$.
]

#algorithm("Double-and-Add for Scalar Multiplication")[
  *Input*: A point $P in E(FF_p)$ and an integer $k > 0$ with binary representation $k=(k_n k_(n-1) ... k_1 k_0)_2$.

  *Output*: $Q = k P$.

  1. Set $Q=cal(O)$ and $R=P$.
  2. For $i=0$ to $n$:
     - If $k_i=1$, set $Q=Q ⊕ R$.
     - Set $R=2 R$.
  3. Return $Q$.

  This requires $O(log k)$ elliptic-curve operations and doublings.
]

#example[
  On the toy curve
  $ E: y^2 equiv x^3 + 2x + 2 space (mod 17) $
  with $G=(5,1)$, compute $13 G$ using double-and-add.

  Since $13=1101_2$, we use the powers
  $ G, 2G, 4G, " and " 8G. $
  The repeated doublings give
  $ 2G=(6,3), quad 4G=(3,1), quad 8G=(13,7). $
  Because
  $ 13G = 8G ⊕ 4G ⊕ G, $
  we combine the selected powers:
  $ 8G ⊕ 4G = (0,11), $
  and then
  $ (0,11) ⊕ G = (16,4). $
  Therefore
  $ 13G=(16,4). $
]

#definition("Base Point and Generated Subgroup")[
  Since $E(FF_p)$ is a finite abelian group, it may contain cyclic subgroups. A *generator* or *base point* $G$ of order $n$ is a point satisfying
  $ n G = cal(O) $
  and no smaller positive multiple of $G$ equals $cal(O)$.

  The subgroup generated by $G$ is
  $ chevron.l G chevron.r = {cal(O), G, 2 G, ..., (n-1) G}. $
]

#example[
  On the toy curve
  $ E: y^2 equiv x^3 + 2x + 2 space (mod 17), $
  the point $G=(5,1)$ lies on the curve because
  $ 1^2 equiv 5^3 + 2 dot 5 + 2 equiv 137 equiv 1 space (mod 17). $

  To prove that $G$ has order $19$, compute its successive multiples:

  #table(
    columns: (auto, auto, auto, auto),
    inset: 5pt,
    align: center,
    table.header([$k$], [$k G$], [$k$], [$k G$]),
    [$1$], [$(5,1)$], [$10$], [$(7,11)$],
    [$2$], [$(6,3)$], [$11$], [$(13,10)$],
    [$3$], [$(10,6)$], [$12$], [$(0,11)$],
    [$4$], [$(3,1)$], [$13$], [$(16,4)$],
    [$5$], [$(9,16)$], [$14$], [$(9,1)$],
    [$6$], [$(16,13)$], [$15$], [$(3,16)$],
    [$7$], [$(0,6)$], [$16$], [$(10,11)$],
    [$8$], [$(13,7)$], [$17$], [$(6,14)$],
    [$9$], [$(7,6)$], [$18$], [$(5,16)$],
    [$19$], [$cal(O)$], [], [],
  )

  The first positive multiple of $G$ equal to $cal(O)$ is $19 G$. Therefore $G$ has order $19$, and the cyclic subgroup generated by $G$ is
  $ chevron.l G chevron.r = {cal(O), G, 2 G, ..., 18 G}. $
]

#definition("Private Key and Public Key")[
  In a key-exchange protocol, a *private key* is information kept secret by one person, while a *public key* is information that may be shared openly.

  For elliptic-curve Diffie-Hellman, the private key is modeled as a secret integer $d$ with
  $ 1 <= d <= n-1, $
  where $n$ is the order of the chosen base point $G$. The corresponding public key is the point
  $ Q = d G. $

  Thus $d$ is private, while $G$ and $Q$ may be public. The point $Q$ can be computed efficiently from $d$, but the security idea is that recovering $d$ from $G$ and $Q$ should be hard on a properly chosen large curve.
]

#example[
  On the same toy curve with base point $G=(5,1)$ of order $19$, choose
  $ d=5. $
  The public point is
  $ Q = d G = 5 G = (9,16). $
  Here $d=5$ is the private key. The base point $G$ and the point $Q=(9,16)$ may be public.
]

#definition("Elliptic Curve Discrete Logarithm Problem")[
  Given a base point $G$ and a public point $Q=d G$, the *Elliptic Curve Discrete Logarithm Problem* (ECDLP) asks one to recover the integer $d$.
]

#example[
  In the same toy subgroup, suppose $G=(5,1)$ and the public point is
  $ Q=(9,16). $
  Since $5 G=(9,16)$, the discrete logarithm of $Q$ with respect to $G$ is
  $ d=5. $
  This can be recognized by checking multiples of $G$ only because the group is tiny; this is not feasible on properly chosen large curves.
]

#note[
  Computing $Q=d G$ from $d$ is efficient by double-and-add. The reverse problem, recovering $d$ from $G$ and $Q$, is the hard direction on properly chosen large curves. This one-way behavior is the algebraic reason elliptic-curve groups are useful in key exchange.
]

#algorithm("Elliptic-Curve Diffie-Hellman")[
  *Public parameters*: an elliptic curve $E(FF_p)$ and a base point $G$ of order $n$.

  1. Alice chooses a private scalar $a$ and publishes
     $ A = a G. $
  2. Bob chooses a private scalar $b$ and publishes
     $ B = b G. $
  3. Alice computes
     $ S_A = a B = a(b G) = a b G. $
  4. Bob computes
     $ S_B = b A = b(a G) = b a G. $
  5. Since integer multiplication commutes, $a b G=b a G$, so both obtain the same shared point
     $ S = a b G. $
]

#example[
  Work on the toy curve
  $ E: y^2 equiv x^3 + 2x + 2 space (mod 17) $
  with base point $G=(5,1)$. This point has order $19$, so the public subgroup is
  $ chevron.l G chevron.r = {cal(O), G, 2 G, ..., 18 G}. $

  Alice chooses the private scalar $a=5$. Her public point is
  $ A = 5 G = (9,16). $

  Bob chooses the private scalar $b=7$. His public point is
  $ B = 7 G = (0,6). $

  Alice receives $B$ and computes
  $ S_A = 5 B = 5(7 G) = 35 G = (10,11). $
  Bob receives $A$ and computes
  $ S_B = 7 A = 7(5 G) = 35 G = (10,11). $

  Thus both parties obtain the same shared point
  $ S=(10,11), $
  even though Alice did not reveal $a$ and Bob did not reveal $b$.
]

#note[
  Real systems use standardized curves, large prime-order subgroups, and implementation rules that prevent small-subgroup or invalid-point attacks. They also pass the shared point through a key-derivation function to obtain a symmetric key. The example above is intentionally small and is only for hand calculation.
]

=== Solved Problems

#solved_problem[
  Explain why double-and-add is efficient for computing $127 P$.
]
#solution[
  Since
  $ 127 = 1111111_2, $
  it has 7 binary digits. Naive repeated use of $⊕$ requires 126 operations. Double-and-add builds the powers
  $ 2 P,4 P,8 P,16 P,32 P,64 P $
  by 6 doublings and then combines the needed terms. This uses about $O(log 127)$ group operations instead of $O(127)$ operations.
]

#solved_problem[
  On the toy curve $E: y^2 equiv x^3 + 2x + 2 space (mod 17)$ with $G=(5,1)$, compute $2 G$, $3 G$, and $10 G$, and verify that $19 G=cal(O)$.
]
#solution[
  *Step 1: $2 G$.* Since $a=2$,
  $ lambda = (3 dot 5^2 + 2)(2 dot 1)^(-1) = 77 dot 2^(-1) equiv 9 dot 9 equiv 13 space (mod 17). $
  Thus
  $ x_3 = 13^2 - 2 dot 5 = 159 equiv 6, $
  $ y_3 = 13(5-6)-1 = -14 equiv 3. $
  Hence $2 G=(6,3)$.

  *Step 2: $3 G=2 G ⊕ G$.* Combine $(6,3)$ and $(5,1)$:
  $ lambda = (1-3)(5-6)^(-1) = (-2)(-1)^(-1) equiv 2 space (mod 17). $
  Hence
  $ x_3 = 2^2 - 6 - 5 = -7 equiv 10, $
  $ y_3 = 2(6-10)-3 = -11 equiv 6. $
  So $3 G=(10,6)$.

  Continuing by the same formulas gives
  $ 10 G=(7,11). $
  Also $18 G=overline(G)=(5,16)$, so
  $ 19 G=18 G ⊕ G=(5,16) ⊕ (5,1)=cal(O), $
  because the two points are inverses.
]

#solved_problem[
  Explain the algebraic idea behind a public key of the form $Q = d G$.
]
#solution[
  The integer $d$ is private, while $G$ and $Q=d G$ may be public. Computing $Q$ from $d$ and $G$ is efficient because scalar multiplication can be done by double-and-add. Recovering $d$ from $G$ and $Q$ is the ECDLP. For carefully chosen large curves, no efficient general method is known for this reverse problem.
]

#solved_problem[
  Verify the toy ECDH exchange on $E: y^2 equiv x^3 + 2x + 2 space (mod 17)$ with $G=(5,1)$, Alice's private scalar $a=5$, and Bob's private scalar $b=7$.
]
#solution[
  From the scalar multiples of $G$ on this curve,
  $ 5 G=(9,16) quad "and" quad 7 G=(0,6). $
  Therefore Alice publishes $A=(9,16)$ and Bob publishes $B=(0,6)$.

  Alice computes
  $ 5 B = 5(7 G) = 35 G. $
  Since $G$ has order $19$,
  $ 35 G = 16 G = (10,11). $

  Bob computes
  $ 7 A = 7(5 G) = 35 G = 16 G = (10,11). $

  Both computations give the same shared point
  $ S=(10,11). $
]

=== Self-Evaluation Quiz

#quiz[
  #question(
    [Scalar multiplication $k P$ is computed efficiently using:],
    (["Trial division"], ["Double-and-add"], ["The Euclidean algorithm only"], ["Point counting"]),
    1,
  )

  #question(
    [A generator $G$ of order $n$ satisfies:],
    ([$G^n=1$], [$n G=cal(O)$], [$G+n=cal(O)$], [$n=\#FF_p$]),
    1,
  )

  #question(
    [The ECDLP asks one to recover:],
    ([$G$ from $Q=d G$], [$Q$ from $d$ and $G$], [$d$ from $G$ and $Q=d G$], [$p$ from $E(FF_p)$]),
    2,
  )

  #question(
    [In ECDH, Alice publishes:],
    ([$a$], [$A=a G$], [$a b G$], [$b A$]),
    1,
  )

  #question(
    [In ECDH, Alice and Bob obtain the same shared point because:],
    ([$a B=a(b G)=a b G$ and $b A=b(a G)=b a G$], [$a=b$ always], [$G=cal(O)$], [$A=B$ always]),
    0,
  )
]

=== Supplementary Problems

#supplementary[
  Compute $3 P$ on $E: y^2 equiv x^3 + x + 1 space (mod 23)$ where $P=(0,1)$ using double-and-add.
]

#supplementary[
  Show that for any point $P$ of order $n$ on $E(FF_p)$, we have $n P=cal(O)$.
]

#supplementary[
  Explain why naive repeated use of $⊕$ is computationally infeasible for a 256-bit scalar $k$.
]

#supplementary[
  On $E(FF_7)$ with $\#E=9$, if $G$ has order $9$, how many distinct points does $chevron.l G chevron.r$ contain?
]

#supplementary[
  In the public-key relation $Q=d G$, explain what is public, what is private, and why recovering $d$ is expected to be hard on a large standardized curve.
]

#supplementary[
  Compare, at a high level, why elliptic-curve cryptography can use smaller keys than RSA for a similar security level.
]

#supplementary[
  On the toy curve $E: y^2 equiv x^3 + 2x + 2 space (mod 17)$ with $G=(5,1)$, run an ECDH exchange where Alice chooses $a=3$ and Bob chooses $b=4$. Compute the public points and the shared point.
]
